=== meroxa/turbine-core/pkg/ir/v1/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema#",
    "$id": "https://api.meroxa.io/spec/v2/turbine.ir.schema.json",
    "title": "Turbine intermediate representation schema",
    "type": "object",
    "properties": {
        "connectors": {
            "type": "array",
            "prefixItems": [
                {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string",
                            "minLength": 1
                        },
                        "uuid": {
                            "type": "string",
                            "minLength": 0,
                            "maxLength": 36
                        },
                        "plugin_type": {
                            "type": "string",
                            "enum": [
                                "source",
                                "destination"
                            ]
                        },
                        "plugin_name": {
                            "type": "string",
                            "minLength": 1
                        },
                        "plugin_config": {
                            "type": "object"
                        }
                    },
                    "required": [
                        "name",
                        "plugin_type",
                        "plugin_name"
                    ]
                }
            ],
            "minItems": 0,
            "uniqueItems": true
        },
        "functions": {
            "type": "array",
            "prefixItems": [
                {
                    "type": "object",
                    "properties": {
                        "uuid": {
                            "type": "string",
                            "minLength": 0,
                            "maxLength": 36
                        },
                        "name": {
                            "type": "string",
                            "pattern": "^[a-zA-Z][a-zA-Z0-9-_]*$"
                        },
                        "image": {
                            "type": "string",
                            "minLength": 1
                        }
                    },
                    "required": [
                        "name",
                        "image"
                    ]
                }
            ],
            "minItems": 0,
			"maxItems": 1,
            "uniqueItems": true
        },
        "streams": {
            "type": "array",
            "prefixItems": [
                {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string",
                            "minLength": 1
                        },
                        "from_uuid": {
                            "type": "string",
                            "minLength": 36,
                            "maxLength": 36
                        },
                        "to_uuid": {
                            "type": "string",
                            "minLength": 36,
                            "maxLength": 36
                        },
                        "uuid": {
                            "type": "string",
                            "minLength": 0,
                            "maxLength": 36
                        }
                    },
                    "required": [
                        "name",
                        "from_uuid",
                        "to_uuid",
                        "uuid"
                    ]
                }
            ],
            "uniqueItems": true
        },
        "secrets": {
            "type": "object"
        },
        "definition": {
            "description": "The extra details about the spec",
            "type": "object",
            "properties": {
                "git_sha": {
                    "description": "The git sha used to generate the spec",
                    "type": "string"
                },
                "metadata": {
                    "description": "The metadata associated with the spec",
                    "type": "object",
                    "properties": {
                        "turbine": {
                            "description": "The turbine details",
                            "type": "object",
                            "properties": {
                                "language": {
                                    "description": "The language used to create deployment",
                                    "type": "string",
                                    "enum": [
                                        "golang",
                                        "javascript",
                                        "js",
                                        "python",
                                        "py",
                                        "ruby"
                                    ]
                                },
                                "version": {
                                    "description": "The version of language used to create deployment",
                                    "type": "string",
                                    "minLength": 1
                                }
                            },
                            "required": [
                                "language",
                                "version"
                            ]
                        },
                        "spec_version": {
                            "description": "The spec version",
                            "type": "string"
                        }
                    },
                    "required": [
                        "turbine",
                        "spec_version"
                    ]
                }
            },
            "required": [
                "git_sha",
                "metadata"
            ]
        }
    },
    "required": [
        "connectors",
        "definition"
    ]
}

=== meroxa/turbine-core/pkg/ir/spectest/0.1.1/spec.json
{
    "secrets": {
        "key": "valuesecret"
    },
    "connectors": [
        {
            "collection": "user_activity",
            "direction": "source",
            "plugin_name": "postgres",
            "config": {
                "logical_replication": true
            }
        },
        {
            "collection": "user_activity_enriched",
            "direction": "destination",
            "plugin_name": "postgres"
        }
    ],
    "functions": [
        {
            "name": "user_activity_enriched",
            "image": "ftorres/enrich:9",
            "env_vars": {
                "CLEARBIT_API_KEY": "token-1"
            }
        }
    ],
    "definition": {
        "git_sha": "3630e05a-98b7-43a0-aeb0-c9b5b0d4261c",
        "metadata": {
            "turbine": {
                "language": "golang",
                "version": "0.1.0"
            },
            "spec_version": "0.1.1"
        }
    }
}

=== meroxa/turbine-core/pkg/ir/spectest/0.3.0/spec.json
{
    "secrets": {
        "key": "valuesecret"
    },
    "connectors": [
        {
            "uuid": "252bc5e1-666e-4985-a12a-42af81a5d2ab",
            "plugin_type": "source",
            "plugin_name": "postgres",
            "plugin_config": {
                "logical_replication": true,
                "collection": "user_activity"
            }
        },
        {
            "uuid": "dde3bf4e-0848-4579-b05d-7e6dcfae61ea",
            "plugin_type": "destination",
            "plugin_name": "postgres",
            "plugin_config": {
                "collection": "user_activity_enriched"
            }
        }
    ],
    "functions": [
        {
            "uuid": "2ff03fff-6f3e-4f7d-aef8-59c9670bb75d",
            "name": "user_activity_enriched",
            "image": "ftorres/enrich:9",
            "env_vars": {
                "CLEARBIT_API_KEY": "token-1"
            }
        }
    ],
    "streams": [
        {
            "uuid": "12345",
            "name": "my_stream1",
            "from_uuid": "252bc5e1-666e-4985-a12a-42af81a5d2ab",
            "to_uuid": "dde3bf4e-0848-4579-b05d-7e6dcfae61ea"
        },
        {
            "uuid": "123456",
            "name": "my_stream2",
            "from_uuid": "dde3bf4e-0848-4579-b05d-7e6dcfae61ea",
            "to_uuid": "2ff03fff-6f3e-4f7d-aef8-59c9670bb75d"
        }
    ],
    "definition": {
        "git_sha": "3630e05a-98b7-43a0-aeb0-c9b5b0d4261c",
        "metadata": {
            "turbine": {
                "language": "golang",
                "version": "0.1.0"
            },
            "spec_version": "0.3.0"
        }
    }
}

=== meroxa/turbine-core/pkg/ir/spectest/spec.json
{
    "secrets": {
        "key": "valuesecret"
    },
    "connectors": [
        {
            "id":"1",
            "collection": "user_activity",
            "type": "source",
            "resource": "mypg",
            "config": {
                "logical_replication": true
            }
        },
        {
            "id":"2",
            "collection": "user_activity_enriched",
            "type": "destination",
            "resource": "mypg"
        }
    ],
    "functions": [
        {
            "id":"3",
            "name": "user_activity_enriched",
            "image": "ftorres/enrich:9",
            "env_vars": {
                "CLEARBIT_API_KEY": "token-1"
            }
        }
    ],
    "streams":[
        {
            "id": "12345",
            "name": "my_stream1",
            "from_id":"1",
            "to_id":"2"
        },
        {
            "id": "123456",
            "name": "my_stream2",
            "from_id":"2",
            "to_id":"3"
        }
    ],
    "definition": {
        "git_sha": "3630e05a-98b7-43a0-aeb0-c9b5b0d4261c",
        "metadata": {
            "turbine": {
                "language": "golang",
                "version": "0.1.0"
            },
            "spec_version": "0.2.0"
        }
    }
}
